USE PokeGrading;
GO

ALTER TABLE USERS
ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE(email);

ALTER TABLE USERS
ADD CONSTRAINT UQ_USERS_ALIAS UNIQUE(alias);

ALTER TABLE ROLES
ADD CONSTRAINT UQ_ROLES_NAME UNIQUE(name);

ALTER TABLE PASSWORD_RESET_TOKENS
ADD CONSTRAINT UQ_PASSWORD_RESET_TOKEN UNIQUE(token);

ALTER TABLE USERS
ADD CONSTRAINT CK_USERS_STATUS
CHECK (status IN ('ACTIVE','SUSPENDED','PENDING_ACTIVATION','EXPIRED'));

ALTER TABLE USERS
ADD CONSTRAINT CK_USERS_LANGUAGE
CHECK (preferred_language IN ('ES','EN'));

ALTER TABLE USERS
ADD CONSTRAINT CK_USERS_COUNTRY
CHECK (country IN ('CR','PA','MX','CO','CL','AR'));

ALTER TABLE ACCOUNT_ACTIVATIONS
ADD CONSTRAINT CK_ACCOUNT_ACTIVATIONS_STATUS
CHECK (status IN ('PENDING','APPROVED','REJECTED','ACTIVATED','EXPIRED'));

ALTER TABLE API_KEYS
ADD CONSTRAINT CK_API_KEY_STATUS
CHECK (status IN ('ACTIVE','ROTATED','REVOKED'));

ALTER TABLE SUBSCRIPTIONS
ADD CONSTRAINT CK_SUBSCRIPTION_DATES
CHECK (start_date <= end_date);

ALTER TABLE B2B_CLIENTS
ADD CONSTRAINT CK_B2B_QUOTA
CHECK (monthly_quota > 0);

ALTER TABLE CARD_VERSIONS
ADD CONSTRAINT CK_CARD_HP
CHECK (hp IS NULL OR hp >= 0);

ALTER TABLE CARD_VERSIONS
ADD CONSTRAINT CK_PSA_GRADE
CHECK (psa_grade IS NULL OR psa_grade BETWEEN 1.0 AND 10.0);

ALTER TABLE IMPORT_BATCHES
ADD CONSTRAINT CK_IMPORT_BATCH_STATUS
CHECK (status IN ('PENDING','VALIDATED','CONFIRMED','PARTIAL','CANCELLED'));

ALTER TABLE IMPORT_BATCH_ITEMS
ADD CONSTRAINT CK_IMPORT_ITEM_STATUS
CHECK (status IN ('VALID','INVALID','DUPLICATE','IMPORTED'));
GO