USE PokeGrading;
GO

ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_ROLES
FOREIGN KEY(role_id)
REFERENCES ROLES(role_id);

ALTER TABLE ACCOUNT_ACTIVATIONS
ADD CONSTRAINT FK_ACTIVATION_USER
FOREIGN KEY(user_id)
REFERENCES USERS(user_id);

ALTER TABLE ACCOUNT_ACTIVATIONS
ADD CONSTRAINT FK_ACTIVATION_CREATED_BY
FOREIGN KEY(created_by)
REFERENCES USERS(user_id);

ALTER TABLE ACCOUNT_ACTIVATIONS
ADD CONSTRAINT FK_ACTIVATION_APPROVED_BY
FOREIGN KEY(approved_by)
REFERENCES USERS(user_id);

ALTER TABLE PASSWORD_RESET_TOKENS
ADD CONSTRAINT FK_PASSWORD_RESET_USER
FOREIGN KEY(user_id)
REFERENCES USERS(user_id);

ALTER TABLE SUBSCRIPTIONS
ADD CONSTRAINT FK_SUBSCRIPTIONS_USER
FOREIGN KEY(user_id)
REFERENCES USERS(user_id);

ALTER TABLE API_KEYS
ADD CONSTRAINT FK_API_KEYS_CLIENT
FOREIGN KEY(client_id)
REFERENCES B2B_CLIENTS(client_id);

ALTER TABLE CARDS
ADD CONSTRAINT FK_CARDS_CREATED_BY
FOREIGN KEY(created_by)
REFERENCES USERS(user_id);

ALTER TABLE CARD_VERSIONS
ADD CONSTRAINT FK_CARD_VERSIONS_CARD
FOREIGN KEY(card_id)
REFERENCES CARDS(card_id);

ALTER TABLE CARD_VERSIONS
ADD CONSTRAINT FK_CARD_VERSIONS_CREATED_BY
FOREIGN KEY(created_by)
REFERENCES USERS(user_id);

ALTER TABLE CARD_IMAGES
ADD CONSTRAINT FK_CARD_IMAGES_VERSION
FOREIGN KEY(version_id)
REFERENCES CARD_VERSIONS(version_id);

ALTER TABLE CARDS
ADD CONSTRAINT FK_CARDS_CURRENT_VERSION
FOREIGN KEY(current_version_id)
REFERENCES CARD_VERSIONS(version_id);

ALTER TABLE IMPORT_BATCHES
ADD CONSTRAINT FK_IMPORT_BATCHES_CREATED_BY
FOREIGN KEY(created_by)
REFERENCES USERS(user_id);

ALTER TABLE IMPORT_BATCH_ITEMS
ADD CONSTRAINT FK_IMPORT_BATCH_ITEMS_BATCH
FOREIGN KEY(batch_id)
REFERENCES IMPORT_BATCHES(batch_id);

ALTER TABLE IMPORT_BATCH_ITEMS
ADD CONSTRAINT FK_IMPORT_BATCH_ITEMS_CARD
FOREIGN KEY(card_id)
REFERENCES CARDS(card_id);

ALTER TABLE AUDIT_LOGS
ADD CONSTRAINT FK_AUDIT_LOGS_USER
FOREIGN KEY(user_id)
REFERENCES USERS(user_id);

ALTER TABLE PLAYBOOK_VERSIONS
ADD CONSTRAINT FK_PLAYBOOK_VERSION
FOREIGN KEY(version_id)
REFERENCES ALGORITHM_VERSIONS(version_id);

ALTER TABLE GRADING
ADD CONSTRAINT FK_GRADING_USER
FOREIGN KEY(user_id)
REFERENCES USERS(user_id);

ALTER TABLE GRADING
ADD CONSTRAINT FK_GRADING_CARD
FOREIGN KEY(card_id)
REFERENCES CARDS(card_id);

ALTER TABLE GRADING
ADD CONSTRAINT FK_GRADING_ALGORITHM
FOREIGN KEY(version_id)
REFERENCES ALGORITHM_VERSIONS(version_id);

ALTER TABLE GRADING_IMAGES
ADD CONSTRAINT FK_GRADING_IMAGES
FOREIGN KEY(grading_id)
REFERENCES GRADING(grading_id);

ALTER TABLE SUBGRADES
ADD CONSTRAINT FK_SUBGRADES_GRADING
FOREIGN KEY(grading_id)
REFERENCES GRADING(grading_id);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEW_GRADING
FOREIGN KEY(grading_id)
REFERENCES GRADING(grading_id);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEW_USER
FOREIGN KEY(reviewer_id)
REFERENCES USERS(user_id);

ALTER TABLE PRICE_ESTIMATES
ADD CONSTRAINT FK_PRICE_ESTIMATE_GRADING
FOREIGN KEY(grading_id)
REFERENCES GRADING(grading_id);
GO