USE PokeGrading;
GO

CREATE INDEX IX_USERS_ROLE
ON USERS(role_id);

CREATE UNIQUE INDEX UX_ACCOUNT_ACTIVATIONS_TOKEN_NOT_NULL
ON ACCOUNT_ACTIVATIONS(token)
WHERE token IS NOT NULL;

CREATE UNIQUE INDEX UX_API_KEYS_HASH_NOT_NULL
ON API_KEYS(api_key_hash)
WHERE api_key_hash IS NOT NULL;

CREATE INDEX IX_SUBSCRIPTIONS_USER
ON SUBSCRIPTIONS(user_id);

CREATE INDEX IX_CARD_VERSIONS_CARD
ON CARD_VERSIONS(card_id);

CREATE INDEX IX_CARD_IMAGES_VERSION
ON CARD_IMAGES(version_id);

CREATE INDEX IX_IMPORT_BATCH_ITEMS_BATCH
ON IMPORT_BATCH_ITEMS(batch_id);

CREATE INDEX IX_AUDIT_LOGS_USER
ON AUDIT_LOGS(user_id);

CREATE INDEX IX_API_KEYS_CLIENT
ON API_KEYS(client_id);
GO