USE PokeGrading;
GO

CREATE INDEX IX_USERS_ROLE
ON USERS(role_id);

CREATE UNIQUE INDEX UX_ACCOUNT_ACTIVATIONS_TOKEN_NOT_NULL
ON ACCOUNT_ACTIVATIONS(token)
WHERE token IS NOT NULL;

CREATE UNIQUE INDEX UX_API_KEYS_HASH_NOT_NULL
ON API_KEYS(api_key_hash)
WHERE api_key_hash IS NOT NULL;

CREATE INDEX IX_SUBSCRIPTIONS_USER
ON SUBSCRIPTIONS(user_id);

CREATE INDEX IX_CARD_VERSIONS_CARD
ON CARD_VERSIONS(card_id);

CREATE INDEX IX_CARD_IMAGES_VERSION
ON CARD_IMAGES(version_id);

CREATE INDEX IX_IMPORT_BATCH_ITEMS_BATCH
ON IMPORT_BATCH_ITEMS(batch_id);

CREATE INDEX IX_AUDIT_LOGS_USER
ON AUDIT_LOGS(user_id);

CREATE INDEX IX_API_KEYS_CLIENT
ON API_KEYS(client_id);
CREATE INDEX IX_GRADING_USER
ON GRADING(user_id);

CREATE INDEX IX_GRADING_CARD
ON GRADING(card_id);

CREATE INDEX IX_GRADING_ALGORITHM
ON GRADING(version_id);

CREATE INDEX IX_REVIEWS_GRADING
ON REVIEWS(grading_id);

CREATE INDEX IX_REVIEWS_REVIEWER
ON REVIEWS(reviewer_id);

CREATE UNIQUE INDEX UX_SUBGRADES_GRADING
ON SUBGRADES(grading_id);

CREATE UNIQUE INDEX UX_PRICE_ESTIMATES_GRADING
ON PRICE_ESTIMATES(grading_id);

CREATE INDEX IX_PLAYBOOK_VERSION
ON PLAYBOOK_VERSIONS(version_id);

CREATE UNIQUE INDEX UX_API_REQUESTS
ON API_REQUESTS
(
    api_key_id,
    external_request_id
);

CREATE INDEX IX_API_REQUESTS_API_KEY
ON API_REQUESTS(api_key_id);

CREATE INDEX IX_API_AUDIT_API_KEY
ON API_AUDIT_LOGS(api_key_id);

CREATE INDEX IX_API_AUDIT_REQUEST
ON API_AUDIT_LOGS(request_id);

CREATE INDEX IX_API_USAGE_CLIENT
ON API_USAGE(client_id);

CREATE INDEX IX_API_USAGE_MONTH
ON API_USAGE(month_year);


GO