USE PokeGrading;
GO

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE role_id = 1)
INSERT INTO ROLES(role_id, name)
VALUES (1, 'SUBMITTER');

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE role_id = 2)
INSERT INTO ROLES(role_id, name)
VALUES (2, 'REVIEWER');

IF NOT EXISTS (SELECT 1 FROM ROLES WHERE role_id = 3)
INSERT INTO ROLES(role_id, name)
VALUES (3, 'ADMIN');

GO